name: cftime test

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [ "3.8"]
        os: [ubuntu-latest]
        platform: [x64, aarch64]
#  debug on a single os/platform/python version
#       python-version: [ "3.9"]
#       os: [ubuntu-latest]
#       platform: [x64]
        #include:
        #  - os: ubuntu18.04
        #    arch: aarch64
        exclude:
          - os: macos-latest  
            platform: x32

    env:
      TRAVIS_BUILD_DIR: ${{ github.workspace }}
      TRAVIS_REPO_SLUG: ${{ github.repository }}

    steps:

    - uses: actions/checkout@v2

    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        activate-conda: false
        conda-channels: conda-forge

    - name: Setup Conda Env
      shell: bash -l {0}
      run: |
        conda create --name TEST python=${{ matrix.python-version }} --file requirements.txt --file requirements-dev.txt
        source activate TEST
        # enabling coverage slows down the tests dramaticaly
        #CYTHON_COVERAGE=1 pip install -v -e  . --no-deps --force-reinstall
        pip install -v -e  . --no-deps --force-reinstall
        conda info --all
        conda list

    - name: Run Tests
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash -l {0}
      run: |
        source activate TEST
        py.test -vv test

#   - name: Coveralls
#     env:
#       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#     if: ${{ matrix.os =='ubuntu-latest' && matrix.python-version == '3.9' && matrix.platform == 'x64' }}
#     run: |
#       source activate TEST
#       coveralls --service=github-actions

    - name: Tarball
      if: startsWith(matrix.os,'ubuntu')
      shell: bash -l {0}
      run: |
        source activate TEST
        python setup.py --version ; 
        pip wheel . -w dist --no-deps ;
        check-manifest --verbose ;
        twine check dist/* ;
 
    - name: Docs
      if: startsWith(matrix.os,'ubuntu')
      shell: bash -l {0}
      run: |
        source activate TEST
        pushd docs && make html linkcheck O=-W && popd;
        #rm -f docs/build/html/_static/jquery-*.js
        #rm -f docs/build/html/_static/underscore-*.js
        #rm -f docs/build/html/.buildinfo
        #sh ./ci/deploy_docs.sh
  run_aarch64:
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu18.04
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: uraimo/run-on-arch-action@v2.0.5
        name: Build artifact
        id: build
        with:
          arch: ${{ matrix.arch }}
          distro: ${{ matrix.distro }}
          setup: |
            mkdir -p "${PWD}/artifacts"
          dockerRunArgs: |
            --volume "${PWD}/artifacts:/artifacts"
          env: | # YAML, but pipe character is necessary
            artifact_name: git-${{ matrix.distro }}_${{ matrix.arch }}
          shell: /bin/sh
          run: |
            uname -m
            ls -l /usr/bin/
            python3 --version
      - name: Setup Conda
        run: uname -m
